### PR TITLE
BRUHH FIX THAT BROKEN KERNEL

### PR DESCRIPTION
**Pull request by JaswantTeja**
Exactly 2 Years ago ,We started Asking for The Fix of That Broken Kernel..
Can't You guys update it or Wot??
Literally So Many RMX1911 Guys Created Issues 2 Years Ago. When You Guys gonna Release the EOL Kernel & Fix The Broken Kernel !!!!

### CODE REVIEW

**Comment by JaswantTeja** [comment]
@realme-kernel-opensource !!!!

**Comment by realme-kernel-opensource** [comment]
Hi,
We have updated the kernel source of the realme5/realme5S/realme5i Android Q, please get the latest code from: https://github.com/realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source.




realme



***@***.***
 
From: Jaswanth Teja
Date: 2022-10-24 19:47
To: realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source
CC: realme-kernel-opensource; Mention
Subject: Re: [realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source] BRUHH FIX THAT BROKEN KERNEL (PR #234)
@realme-kernel-opensource !!!!

**Comment by JaswantTeja** [comment]
> Hi, We have updated the kernel source of the realme5/realme5S/realme5i Android Q, please get the latest code from: https://github.com/realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source. realme ***@***.*** From: Jaswanth Teja Date: 2022-10-24 19:47 To: realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source CC: realme-kernel-opensource; Mention Subject: Re: [realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source] BRUHH FIX THAT BROKEN KERNEL (PR #234) @realme-kernel-opensource !!!! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

@realme-kernel-opensource I Can't See any latest commit there!! How You guys Think That We can use a broken Kernel??

**Comment by JaswantTeja** [comment]
> Hi, We have updated the kernel source of the realme5/realme5S/realme5i Android Q, please get the latest code from: https://github.com/realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source. realme ***@***.*** From: Jaswanth Teja Date: 2022-10-24 19:47 To: realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source CC: realme-kernel-opensource; Mention Subject: Re: [realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source] BRUHH FIX THAT BROKEN KERNEL (PR #234) @realme-kernel-opensource !!!! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

@realme-kernel-opensource has poor customer support. I Raised an PR for a Vaild Reason & Got Reply after 2 Days : ! .

**Comment by JaswantTeja** [comment]
@realme-kernel-opensource Here,The Thing is We Got Android Q Source But That is Broken Source.So We can't use that source. Update or Fix the Source ASAP !! 🤧

**Comment by realme-kernel-opensource** [comment]
Hi,
We have updated code, please download the latest code and try again.



realme



***@***.***
 
From: Jaswanth Teja
Date: 2022-10-26 21:39
To: realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source
CC: realme-kernel-opensource; Mention
Subject: Re: [realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source] BRUHH FIX THAT BROKEN KERNEL (PR #234)
@realme-kernel-opensource Here,The Thing is We Got Android Q Source But That is Broken Source.So We can't use that source. Update or Fix the Source ASAP !!

**Comment by JaswantTeja** [comment]
> Hi, We have updated code, please download the latest code and try again. realme ***@***.*** From: Jaswanth Teja Date: 2022-10-26 21:39 To: realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source CC: realme-kernel-opensource; Mention Subject: Re: [realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source] BRUHH FIX THAT BROKEN KERNEL (PR #234) @realme-kernel-opensource Here,The Thing is We Got Android Q Source But That is Broken Source.So We can't use that source. Update or Fix the Source ASAP !! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

@realme-kernel-opensource I have tried this source for 2 times and still it is broken. So please release the Last Updated Source (c 79).

**Comment by JaswantTeja** [comment]
> Hi, We have updated code, please download the latest code and try again. realme ***@***.*** From: Jaswanth Teja Date: 2022-10-26 21:39 To: realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source CC: realme-kernel-opensource; Mention Subject: Re: [realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source] BRUHH FIX THAT BROKEN KERNEL (PR #234) @realme-kernel-opensource Here,The Thing is We Got Android Q Source But That is Broken Source.So We can't use that source. Update or Fix the Source ASAP !! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Still same broken thing @realme-kernel-opensource please release c79 Q Source

**Comment by JaswantTeja** [comment]
@realme-kernel-opensource Bro Please look into this issue

**Comment by realme-kernel-opensource** [comment]
Hi,
We have released the kernel source of the realme 5 Android R, you can get it from: https://github.com/realme-kernel-opensource/realme_Q_3pro_5pro_X_XT-AndroidR-kernel-source.




realme



***@***.***
 
From: Jaswanth Teja
Date: 2022-11-06 09:20
To: realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source
CC: realme-kernel-opensource; Mention
Subject: Re: [realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source] BRUHH FIX THAT BROKEN KERNEL (PR #234)
@realme-kernel-opensource Bro Please look into this issue

**Comment by JaswantTeja** [comment]
> Hi, We have released the kernel source of the realme 5 Android R, you can get it from: https://github.com/realme-kernel-opensource/realme_Q_3pro_5pro_X_XT-AndroidR-kernel-source. realme ***@***.*** From: Jaswanth Teja Date: 2022-11-06 09:20 To: realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source CC: realme-kernel-opensource; Mention Subject: Re: [realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source] BRUHH FIX THAT BROKEN KERNEL (PR #234) @realme-kernel-opensource Bro Please look into this issue — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

@realme-kernel-opensource Imao, I'm asking for Realme 5 (RMX1911,2030,1927) Android Q Source but you guys sending me the Android R Source of Realme 5 Pro.

**Comment by JaswantTeja** [comment]
@realme-kernel-opensource atleast push the Narzo20A Kernel 🤧

**Comment by realme-kernel-opensource** [comment]
Hi,
You can get the kernel source of the realme Narzo 20A android Q from: https://github.com/realme-kernel-opensource/realmenarzo20A_AndroidQ-kernel-source.




realme



***@***.***
 
From: Jaswanth Teja
Date: 2022-11-13 13:23
To: realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source
CC: realme-kernel-opensource; Mention
Subject: Re: [realme-kernel-opensource/realme5_realme5S_realme5i_AndroidQ-kernel-source] BRUHH FIX THAT BROKEN KERNEL (PR #234)
@realme-kernel-opensource atleast push the Narzo20A Kernel

**Comment by sarthakroy2002** [comment]
Please push narzo 20A R kernel sources @realme-kernel-opensource

**Comment by JaswantTeja** [comment]
> Please push narzo 20A R kernel sources @realme-kernel-opensource

+

**Comment by JaswantTeja** [comment]
> Please push narzo 20A R kernel sources @realme-kernel-opensource

Yes Please

**Comment by JaswantTeja** [comment]
@realme-kernel-opensource please push c.81 or c.83 kernel Source!

**Pull request closed without merging**
